#   ########################################################################
#   Copyright 2021 Splunk Inc.
#
#    Licensed under the Apache License, Version 2.0 (the "License");
#    you may not use this file except in compliance with the License.
#    You may obtain a copy of the License at
#
#        http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS,
#    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#    See the License for the specific language governing permissions and
#    limitations under the License.
#   ########################################################################

name: cd-github
on:
  push:
    branches-ignore:
      - "**"  
    tags:
      - "v*"
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: false
      - name: Setup regctl
        run: |
          curl -L https://github.com/regclient/regclient/releases/download/v0.3.5/regctl-linux-amd64 >/tmp/regctl
          chmod 755 /tmp/regctl
      - name: Login to GitHub Packages Docker Registry
        uses: docker/login-action@v1.10.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Docker meta
        id: docker_action_meta
        uses: docker/metadata-action@v3
        with:
          images: docker.io/splunk/scs
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern=v{{version}}
            type=semver,pattern=v{{major}}.{{minor}}
            type=semver,pattern=v{{major}}
            type=ref,event=branch
            type=ref,event=pr
            type=sha
            type=sha,format=long
      - id: Pull
        name: Pull Container
        run: |
          VERSION=$(cat package/etc/VERSION)
          echo Pulling $VERSION
          docker pull ghcr.io/splunk/splunk-connect-for-syslog/splunk-connect-for-syslog:$VERSION

          tags=$(echo $CONTAINER_SOURCE_IMAGE |sed 's|ghcr.io/splunk/splunk-connect-for-syslog/splunk-connect-for-syslog|docker.io/splunk/scs|g')
          /tmp/regctl image copy $CONTAINER_SOURCE_IMAGE docker.io/splunk/scs:$1
          for line in $tags; do echo working on "$line"; /tmp/regctl image copy docker.io/splunk/scs:$1 $line; done
        env:
          CONTAINER_SOURCE_IMAGE: ${{ needs.meta.outputs.sc4s}}
          CONTAINER_SOURCE_TAGS: ${{ needs.meta.outputs.container_tags }}
