name: cd-pages-helm

on:
  push:
    branches-ignore:
      - "**"
    tags:
      - "v*"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.6.3
      - name: Install CR
        run: |
          brew tap helm/tap
          brew install chart-releaser
      - name: Package
        run: |
          cr package charts/splunk-connect-for-syslog
      - name: Upload release binaries
        uses: alexellis/upload-assets@0.2.2
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          asset_paths: '[".cr-release-packages/*"]'
