name: Release-Notes-Preview

on:
  pull_request:
  #    branches: [main, develop]
  issue_comment:
    types: [edited]

permissions:
  actions: read
  contents: write

jobs:
  call-workflow-preview:
    permissions:
      contents: write
      packages: write
    uses: splunk/addonfactory-github-workflows/.github/workflows/reusable-release-notes.yaml@v1.3.4
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
